# Generated by Django 4.0.4 on 2022-05-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('paragraph', 'paragraph'), ('header', 'header'), ('list', 'list'), ('delimiter', 'delimiter'), ('image', 'image')], default='paragraph', max_length=9)),
                ('data', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockPublicationThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.block')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.ManyToManyField(through='notes.BlockPublicationThroughModel', to='notes.block')),
            ],
        ),
        migrations.AddField(
            model_name='blockpublicationthroughmodel',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.publication'),
        ),
    ]
