"""
django-simple-history settings.
"""

# SIMPLE_HISTORY_HISTORY_CHANGE_REASON_USE_TEXT_FIELD = False
SIMPLE_HISTORY_HISTORY_ID_USE_UUID = True  # Default: False
SIMPLE_HISTORY_FILEFIELD_TO_CHARFIELD = True  # Default: False
# SIMPLE_HISTORY_REVERT_DISABLED = False
