# Generated by Django 3.2.8 on 2022-01-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='description',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='description_en',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='description_fr',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='tagline',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, null=True, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='tagline_fr',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, null=True, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='description',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='description_en',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='description_fr',
            field=models.TextField(blank=True, help_text='A short text to describe this very website.', max_length=2048, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='tagline',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, null=True, verbose_name='tagline'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='tagline_fr',
            field=models.CharField(blank=True, help_text='A few words to describe this very website.', max_length=255, null=True, verbose_name='tagline'),
        ),
    ]
