# Generated by Django 4.0.5 on 2022-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220109_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical site', 'verbose_name_plural': 'historical sites'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitecustomization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical site customization', 'verbose_name_plural': 'historical site customizations'},
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsitecustomization',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
